/*
体系结构
逻辑结构
	表空间
	段、区、块
安全管理
	网络管理 netmgr netca

	客户端:	tnsnames.ora 
			export DISPLAY=192.168.21.1:0.0、netmgr配置
			也可以直接修改tnsnames.ora
	服务器:	listener.ora host/pro/port(netmgr/netca/直接编辑listener.ora) 
			要知道有那些服务(lsnrctl stat)
			配置：alter system set service_names='orcl,prod';　
			[oracle@oracle admin]$ cat listener.ora 
			# listener.ora Network Configuration File: /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora
			# Generated by Oracle configuration tools.

			LISTENER =
			  (DESCRIPTION =
				(ADDRESS = (PROTOCOL = TCP)(HOST = oracle.example.com)(PORT = 1521))
			  )

			ADR_BASE_LISTENER = /u01/app/oracle

			[oracle@oracle admin]$ echo $ORACLE_SID
			orcl
			[oracle@oracle admin]$ hostname
			oracle.example.com
			
			[oracle@oracle ~]$ sqlplus / as sysdba;
			SQL> show parameter name

			NAME                                 TYPE        VALUE
			------------------------------------ ----------- ------------------------------
			db_file_name_convert                 string
			db_name                              string      orcl		数据库名(不区分大小写)
			db_unique_name                       string      orcl		DG环境中用到的
			global_names                         boolean     FALSE		全局数据库名=db_name+db_domain(是否引用全局数据库名，很少用)
			instance_name                        string      orcl		实例名(不区分大小写)
			lock_name_space                      string
			log_file_name_convert                string
			processor_group_name                 string
			service_names                        string      orcl
			SQL> show parameter db_domain

			NAME                                 TYPE        VALUE
			------------------------------------ ----------- ------------------------------
			db_domain                            string					域名
			[oracle@oracle ~]$ lsnrctl stat（lsnrctl status）

			LSNRCTL for Linux: Version 11.2.0.3.0 - Production on 14-FEB-2017 07:35:02

			Copyright (c) 1991, 2011, Oracle.  All rights reserved.

			Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle.example.com)(PORT=1521)))
			STATUS of the LISTENER
			------------------------
			Alias                     LISTENER
			Version                   TNSLSNR for Linux: Version 11.2.0.3.0 - Production
			Start Date                10-FEB-2017 23:16:07
			Uptime                    3 days 8 hr. 18 min. 56 sec
			Trace Level               off
			Security                  ON: Local OS Authentication
			SNMP                      OFF
			Listener Parameter File   /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora
			Listener Log File         /u01/app/oracle/diag/tnslsnr/oracle/listener/alert/log.xml
			Listening Endpoints Summary...
			  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=oracle.example.com)(PORT=1521)))
			Services Summary...
			Service "orcl" has 1 instance(s).
			  Instance "orcl", status READY, has 1 handler(s) for this service...
			The command completed successfully
			SQL> alter system set service_names='orcl,prod';
			[oracle@oracle ~]$ export DISPLAY=192.168.21.1:0.0
			[oracle@oracle ~]$ netmgr　增加一个监听 service name: prod/Host Name:oracle.example.com/port:1521
			[oracle@oracle admin]$ more tnsnames.ora 这个文件是配置在客户端的
			# tnsnames.ora Network Configuration File: /u01/app/oracle/product/11.2.0/db_1/network/admin/tnsnames.ora
			# Generated by Oracle configuration tools.

			ORCL_S =
			  (DESCRIPTION =
				(ADDRESS_LIST =
				  (ADDRESS = (PROTOCOL = TCP)(HOST = oracle.example.com)(PORT = 1521))
				)
				(CONNECT_DATA =
				  (SERVICE_NAME = prod)
				)
			  )
			[oracle@oracle admin]$ tnsping orcl_s
			[oracle@oracle admin]$ sqlplus system/oracle@oracle.example.com:1521/orcl
			[oracle@oracle admin]$ sqlplus system/oracle@orcl_s

注册
	静态注册:预先保存数据库信息
		默认端口、非默认端口：修改listener.ora文件
	动态注册:实例启动后pmon注册（shutdown immediate、ps -ef | grep ora_）
			1521:pmon进程自动注册
			非默认：需要手工修改local_listener参数 alter system set local_listener='ORCL_S2';

	shutdown immediate
	lsnrctl stat(The listener supports no services)
	sqlplus system/oracle@orcl_s(ORA-12514: TNS:listener does not currently know of service requested in connect descriptor)
	startup nomount(shutdown->nomount 启动进程、分配内存)
	lsnrctl stat(Instance "orcl", status BLOCKED, has 1 handler(s) for this service...)
	sqlplus system/oracle@orcl_s(ORA-12528: TNS:listener: all appropriate instances are blocking new connections)
	alter database mount;
	lsnrctl stat(Instance "orcl", status READY, has 1 handler(s) for this service...)
	sqlplus sys/oracle@orcl_s as sysdba(Connected to)
	
	SQL> shutdown immediate
	[oracle@oracle ~]$ more /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora
	# listener.ora Network Configuration File: /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora
	# Generated by Oracle configuration tools.

	LSNR1=
	  (DESCRIPTION =
		(ADDRESS_LIST=
		 (ADDRESS = (PROTOCOL = TCP)(HOST = oracle.example.com)(PORT = 1521))
		)
	  )

	SID_LIST_LSNR1=
	 (SID_LIST=
	   (SID_DESC=
		  (GLOBAL_DBNAME=orcl)
		  (ORACLE_HOME=/u01/app/oracle/product/11.2.0/db_1)
		  (SID_NAME=orcl)
		 )
	 )
	lsnrctl start lsnr1（只有默认的监听名字才可以省掉 listener,port:1521）
	lsnrctl status(Instance "orcl", status UNKNOWN, has 1 handler(s) for this service...)
	[oracle@oracle ~]$ sqlplus sys/oracle@orcl_s as sysdba(Connected to an idle instance.)
	
	修改默认端口
	sqlplus sys/oracle@orcl_s2 as sysdba
	
	服务器端:监听listener.ora
		主机名、端口、协议
		服务名：数据库库（实例）
		监听要注册服务
			静态注册:在listener.ora里配置 
			动态注册:　	默认端口，由pmon自动注册
							alter system register;
						非默认端口，需要修改local_listener参数（tnsnames里的名字、address）
							alter system set local_listener='ORCL_S2';
							或者alter system set local_listener='(ADDRESS = (PROTOCOL = TCP)(HOST = oracle.example.com)(PORT = 1522))';
	客户端:tnsnames.ora
		主机名、端口、协议、服务名：数据库库（实例）->网络服务名、别名
		[oracle@oracle ~]$ vi /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora 
		# listener.ora Network Configuration File: /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora
		# Generated by Oracle configuration tools.

		LSNR1=
		  (DESCRIPTION =
			(ADDRESS_LIST=
			 (ADDRESS = (PROTOCOL = TCP)(HOST = oracle.example.com)(PORT = 1521))
			)
		  )

		SID_LIST_LSNR1=
		 (SID_LIST=
		   (SID_DESC=
			  (GLOBAL_DBNAME=orcl)
			  (ORACLE_HOME=/u01/app/oracle/product/11.2.0/db_1)
			  (SID_NAME=orcl)
			 )
		 )

		LSNR2=
		  (DESCRIPTION =
			(ADDRESS_LIST=
			 (ADDRESS = (PROTOCOL = TCP)(HOST = oracle.example.com)(PORT = 1522))
			)
		  )

		SID_LIST_LSNR2=
		 (SID_LIST=
		   (SID_DESC=
			  (GLOBAL_DBNAME=prod)
			  (ORACLE_HOME=/u01/app/oracle/product/11.2.0/db_1)
			  (SID_NAME=prod)
			 )
		 )

		[oracle@oracle ~]$ lsnrctl reload lsnr2
		[oracle@oracle ~]$ lsnrctl status lsnr2
		sqlplus sys/oracle@orcl_s2 as sysdba
*/
clear screen --清屏
create user u02 identified by oracle;
grant sysdba to u02;
conn u02/oracle
show user--此时显示USER is "U02"
conn u02/oracle as sysdba
show user--此时显示USER is "SYS"
--查看审计文件
cd /u01/app/oracle/admin/orcl/adump/
--口令文件
$ORACLE_HOME/dbs/orapwSID
ls /u01/app/oracle/product/11.2.0/db_1/dbs/orapworcl
--不允许远程登陆
 alter system set remote_login_passwordfile='none' scope=spfile;  
 
/*
linux 中password存放用户
more /etc/passwd　
linux 中password存放密码
more /etc/shadow

select profile from dba_users where username='U01';

SQL> select * from  dba_profiles where profile='DEFAULT';
SQL> col profile for a10
SQL> col limit for a10
SQL> /
*/

[oracle@oracle install]$ emctl start dbconsole
OLAP:查询    u01,hr
OLTP:增删改  OE
window 1-5  OLTP 70% OLAP 20% other 10%  
window 6-7  OLTP 20% OLAP 70% other 10%

create user u01
identified by 123456
default tablespace users
temporary tablespace temp
quota 10m on users
password expire;

ORA-01045: user U03 lacks CREATE SESSION privilege; logon denied
grant connect to u03;
grant create table to u03;
create table t1(id number);
SQL> insert into t1 values(1);
ORA-01950: no privileges on tablespace 'USERS'
SQL> insert into u03.t1 values(1);
ORA-01950: no privileges on tablespace 'USERS'
SQL> alter user u03 quota 10m on users;
权限：
	系统：create session、create tablespace
	对象
	
create table hwm as select * from dba_objects;
select segment_name,segment_type,blocks from dba_segments where segment_name='HWM';
analyze table hwm estimate statistics;
select table_name,num_rows,blocks,empty_blocks from dba_tables where table_name='HWM';
--有多少块容纳数据
select count(distinct dbms_rowid.rowid_block_number(rowid)||dbms_rowid.rowid_relative_fno(rowid)) "used" from hwm;
set timing on
delete from hwm;
commit;
--没变
select table_name,num_rows,blocks,empty_blocks from dba_tables where table_name='HWM';
--0块容纳数据
select count(distinct dbms_rowid.rowid_block_number(rowid)||dbms_rowid.rowid_relative_fno(rowid)) "used" from hwm;

--对比可以理解truncate把水位线降下来了
SQL> create table hwm1 as select * from dba_objects;
SQL> select segment_name,segment_type,blocks from dba_segments where segment_name='HWM1';
SQL> analyze table hwm1 estimate statistics;
SQL> select table_name,num_rows,blocks,empty_blocks from dba_tables where table_name='HWM1';
SQL> select count(distinct dbms_rowid.rowid_block_number(rowid)||dbms_rowid.rowid_relative_fno(rowid)) "used" from hwm1;
SQL> truncate table hwm1;
SQL> analyze table hwm1 estimate statistics ;
SQL> select table_name,num_rows,blocks,empty_blocks from dba_tables where table_name='HWM1';

